SELECT A.CART_ID 
FROM (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Yogurt') A, (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = 'Milk') B
WHERE A.CART_ID = B.CART_ID
--Oracle
SELECT A.CART_ID FROM 
 (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = '요거트') as A, 
 (SELECT CART_ID FROM CART_PRODUCTS WHERE NAME = '우유') as B
 WHERE A.CART_ID = B.CART_ID
 --Mysql